### PR TITLE
Add PHP 8.4

### PR DESCRIPTION
**Pull request by heddn**

### CODE REVIEW

**Comment by fideloper** [comment]
Hey there! Thanks - can you please also add a new file here?  https://github.com/fly-apps/laravel-docker/tree/main/src/php/packages

**Comment by heddn** [comment]
> Hey there! Thanks - can you please also add a new file here? https://github.com/fly-apps/laravel-docker/tree/main/src/php/packages

Done

**Comment by fideloper** [comment]
Thanks again!

Sorry to be annoying (one more request). I just updated branch `main` with a new github action workflow to run some builds against PR's so we can be sure it works.

Would you mind:

1. updating your PR from `main` (it adds a new workflow file) - so it'll run a test build
2. Updating the readme to include mention of php8.4

I appreciate it!

**Comment by fideloper** [comment]
Looks like `php8.4-swoole` doesn't exist yet, perhaps we just leave it out for now.

**Comment by fideloper** [comment]
That passed, sweet!

**Comment by fideloper** [comment]
Thanks for your help there, let's get this out and see how it does.

**Pull request merged**
