### PR TITLE
Add support for PHP 8.3

### PR DESCRIPTION
**Pull request by jonathan-lewerissa**
Added support for PHP8.3

Do I need to update the [Dockerfile](https://github.com/fly-apps/laravel-docker/blob/716bd66c192979e7a573c01924d0c1879f2933ff/src/Dockerfile#L3C1-L3C22 ) and [Dockerfile-unit](https://github.com/fly-apps/laravel-docker/blob/716bd66c192979e7a573c01924d0c1879f2933ff/src/Dockerfile-unit#L3) default args as well?

### CODE REVIEW

**Comment by fideloper** [comment]
Hi!
I think we can leave those at 8.2 for now.

Note that this script needs updating as well (may as well do it in the PR!) https://github.com/fly-apps/laravel-docker/blob/main/build.sh#L12

Did you get a chance to test that out? Some packages are not yet ready for php 8.3 (most notably `php8.3-redis`). We COULD get php 8.3 built ahead of those, I was hoping they'd come out soon.

**Comment by jonathan-lewerissa** [comment]
I've updated the [build](https://github.com/jonathan-lewerissa/laravel-docker/blob/main/build.sh#L12-L13) script as well. [https://github.com/fly-apps/laravel-docker/pull/7/files#diff-4d2a8eefdf2a9783512a35da4dc7676a66404b6f3826a8af9aad038722da6823L12-R13](https://github.com/fly-apps/laravel-docker/pull/7/files#diff-4d2a8eefdf2a9783512a35da4dc7676a66404b6f3826a8af9aad038722da6823L12-R13)

I've only tested the update locally, but can probably make an updated deployment (will send the link).

Also for the packages `php-redis, php-swoole`, it should be available now [https://github.com/oerdnj/deb.sury.org/issues/2034](https://github.com/oerdnj/deb.sury.org/issues/2034)

**Comment by jonathan-lewerissa** [comment]
Tested the image here: https://834a6ff9-ea77-4f95-82a7-ced4437a86b4.fly.dev/

**Comment by fideloper** [comment]
Thank you! I appreciate you taking the time on this!

**Pull request merged**
